sudo: required
before_install:
  - sudo pip install --upgrade pip
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.2
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
language: node_js
node_js:
  - "8.10"
install:
  - yarn install
